//! Static-heavy debuggee for the `statics_enumerate` / `stepping`
//! benches. The 4000 statics are generated by `build.rs` into nested
//! modules `m0..m40`; see that file for the rationale.
include!(concat!(env!("OUT_DIR"), "/statics.rs"));

use core::sync::atomic::Ordering;

fn main() {
    // Touch one of each flavour so nothing surprising gets stripped
    // despite `#[used]`, and so there's a live line to break on with
    // all the module statics in scope.
    let sum = m0::RO_0 + m39::RW_49.load(Ordering::Relaxed);
    println!("{sum}"); // breakpoint line (line 14)
}
