// SPDX-License-Identifier: MIT
//! `bs --record <out.json5> [<debuggee>]` — capture a debugging
//! session as a runnable test script.
//!
//! Reads JSON-RPC requests on stdin (same wire format as `--script`),
//! dispatches them, and writes a parallel `.json5` to `out.json5` that:
//!
//! * preserves every command the user sent verbatim, and
//! * promotes each read-only inspection (`var`, `arg`, `frame.info`)
//!   into a corresponding `assert.*` request whose `expect:` block
//!   carries the response we just observed.
//!
//! The standard JSON-RPC response stream still goes to stdout, so an
//! interactive agent or human caller is unaffected. Replaying the
//! generated script with `bs --test out.json5` should pass —
//! tautologically the first time, then meaningfully after the
//! debugger or debuggee changes.
//!
//! ## What this is not
//!
//! V1 records the JSON-RPC channel. Recording an *interactive console
//! session* (typing `break X` at the `(bs)` prompt and getting a
//! script out) is V2 — the console parser would need to lower to the
//! structured methods first, and that's a wider piece of work.

use std::fs::File;
use std::io::{self, Read, Write};
use std::path::Path;
use std::sync::{Arc, Mutex};
use std::thread;

use os_pipe::PipeReader;
use serde_json::Value;

use crate::debugger::{Debugger, DebuggerBuilder};
use crate::ui::structured::ResponseBudget;
use crate::ui::supervisor::DebugeeSource;

use super::bless;
use super::dispatch;
use super::hook::ScriptHook;
use super::transport::{OutputSink, RequestReader};

/// Run an interactive recording session. Returns when stdin closes.
pub fn run_record(
    out_path: &Path,
    source: DebugeeSource<'_>,
    oracles: Vec<String>,
    address_mask: bool,
) -> anyhow::Result<()> {
    let out_file = File::create(out_path)
        .map_err(|e| anyhow::anyhow!("failed to open {} for writing: {e}", out_path.display()))?;
    let out_file = Arc::new(Mutex::new(out_file));

    // Header sets expectations for whoever opens the file later.
    {
        let mut f = out_file.lock().unwrap();
        writeln!(f, "// Auto-generated by `bs --record`. Edit by hand or")?;
        writeln!(f, "// rerun with `bs --test --bless <this-file>` to refresh")?;
        writeln!(f, "// expectations.")?;
    }

    let stdout = io::stdout();
    let stdout_sink = OutputSink::new(stdout);
    let event_sink = stdout_sink.clone();

    let (out_reader, out_writer) = os_pipe::pipe()?;
    let (err_reader, err_writer) = os_pipe::pipe()?;
    spawn_drain(out_reader);
    spawn_drain(err_reader);

    let child = source.create_child(out_writer, err_writer)?;
    let oracle_objs = crate::ui::supervisor::resolve_oracles(&oracles);

    let mut dbg: Debugger = DebuggerBuilder::new()
        .with_hooks(ScriptHook::new(event_sink))
        .with_oracles(oracle_objs)
        .build(child)?;

    let stdin = io::stdin();
    let mut reader = RequestReader::new(stdin.lock());

    loop {
        match reader.read() {
            Ok(None) => break,
            Err((id, err)) => {
                stdout_sink.emit_response_err(id, err);
            }
            Ok(Some(req)) => {
                let budget = ResponseBudget {
                    max_response_bytes: req.max_response_bytes,
                    include_timestamps: false,
                };
                let method = req.method.clone();
                let result = dispatch::run(&method, &req.params, &mut dbg, &budget);
                let id = req.id.clone();

                let mut script = out_file.lock().unwrap();
                writeln!(script)?;
                emit_request(&mut *script, &method, &req.params)?;

                match &result {
                    Ok(value) => {
                        if let Some(assert_block) = promote_to_assert(&method, &req.params, value, address_mask) {
                            writeln!(script, "{}", assert_block)?;
                        }
                    }
                    Err(_) => {
                        // Failed requests don't get a captured assert
                        // — the response is an error envelope and
                        // there's nothing to pin behaviour against.
                    }
                }
                script.flush()?;
                drop(script);

                let Some(id) = id else { continue };
                match result {
                    Ok(value) => stdout_sink.emit_response_ok(id, value),
                    Err(err) => stdout_sink.emit_response_err(id, err),
                }
            }
        }
    }

    Ok(())
}

/// Emit the verbatim request to the script file. We re-serialise from
/// the parsed `params` rather than copying the raw input bytes — the
/// reader has already discarded comments / formatting, and emitting
/// a canonical JSON5 representation keeps the file linter-friendly.
fn emit_request<W: Write>(out: &mut W, method: &str, params: &Value) -> io::Result<()> {
    let params_text = bless::render_json5_value(params, 2);
    writeln!(out, "{{ method: {}, params: {} }}", json_string(method), params_text)
}

/// If the method has a natural `assert.*` counterpart, render an
/// assertion that pins the captured response. Returns `None` for
/// methods we don't yet auto-promote (stateful commands and
/// pre-existing asserts).
fn promote_to_assert(
    method: &str,
    params: &Value,
    response: &Value,
    address_mask: bool,
) -> Option<String> {
    let (assert_method, assert_params) = match method {
        "var" => ("assert.var", params.clone()),
        "arg" => ("assert.arg", params.clone()),
        "frame.info" => ("assert.frame", Value::Object(Default::default())),
        // Anything else — `break.set`, `run`, `continue`, `assert.*`
        // itself, etc. — doesn't get auto-promoted.
        _ => return None,
    };
    let captured = if address_mask {
        bless::mask_addresses(response.clone())
    } else {
        response.clone()
    };
    // Merge the assert params with an `expect:` field.
    let mut params_obj = match assert_params {
        Value::Object(o) => o,
        _ => Default::default(),
    };
    params_obj.insert("expect".to_string(), captured);
    let params_value = Value::Object(params_obj);
    let body = bless::render_json5_value(&params_value, 2);
    Some(format!(
        "{{ method: {}, params: {} }}",
        json_string(assert_method),
        body
    ))
}

fn json_string(s: &str) -> String {
    serde_json::Value::String(s.to_string()).to_string()
}

fn spawn_drain(mut reader: PipeReader) {
    thread::spawn(move || {
        let mut buf = [0u8; 4096];
        loop {
            match reader.read(&mut buf) {
                Ok(0) | Err(_) => break,
                Ok(_) => continue,
            }
        }
    });
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn promote_var_to_assert_var() {
        let body = promote_to_assert(
            "var",
            &json!({ "name": "x" }),
            &json!({ "items": [{ "value_text": "i32(7)" }] }),
            false,
        )
        .unwrap();
        assert!(body.starts_with("{ method: \"assert.var\""));
        assert!(body.contains("name: \"x\""));
        assert!(body.contains("expect:"));
        assert!(body.contains("\"i32(7)\""));
    }

    #[test]
    fn promote_skips_state_changing_commands() {
        assert!(promote_to_assert("run", &json!({}), &json!({}), false).is_none());
        assert!(promote_to_assert("break.set", &json!({}), &json!({}), false).is_none());
        // Pre-existing assertions aren't re-promoted.
        assert!(promote_to_assert("assert.var", &json!({}), &json!({}), false).is_none());
    }

    #[test]
    fn address_mask_applied_when_enabled() {
        let body = promote_to_assert(
            "var",
            &json!({ "name": "ptr" }),
            &json!({ "items": [{ "value_text": "0xDEADBEEF" }] }),
            true,
        )
        .unwrap();
        assert!(body.contains("$regex"));
        assert!(!body.contains("\"0xDEADBEEF\""));
    }
}
